//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storenarm2.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Message
    {
        public int Message_ID { get; set; }
        public int Message_UserGet { get; set; }
        public Nullable<int> Message_UserSend { get; set; }
        public System.DateTime Message_Date { get; set; }
        public bool Message_Read { get; set; }
        public string Message_Title { get; set; }
        public string Message_Body { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
        public virtual Tbl_User Tbl_User1 { get; set; }
    }
}
