//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storenarm2.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Tags
    {
        public int Tag_ID { get; set; }
        public string Tag_Name { get; set; }
        public int Tag_Proid { get; set; }
    
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
