//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storenarm2.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Withdrawal
    {
        public int Withdrawal_ID { get; set; }
        public System.DateTime Withdrawal_TimeLastReceived { get; set; }
        public int Withdrawal_Stock { get; set; }
        public int Withdrawal_LastReceived { get; set; }
        public bool Withdrawal_Requset { get; set; }
        public int Withdrawal_AmountRequested { get; set; }
        public int Withdrawal_Userid { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
