//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storenarm2.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Download
    {
        public int Download_ID { get; set; }
        public string Download_Url { get; set; }
        public System.DateTime Download_Date { get; set; }
        public int Download_Length { get; set; }
        public bool Download_Allow { get; set; }
        public int Download_Userid { get; set; }
        public Nullable<int> Download_Productid { get; set; }
    
        public virtual Tbl_Product Tbl_Product { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
