//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storenarm2.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Visit
    {
        public int VisitID { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string VisitIP { get; set; }
        public string VisitUsername { get; set; }
        public string VisitBrowser { get; set; }
    }
}
