//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storenarm2.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_NoBank
    {
        public int Banks_ID { get; set; }
        public string Banks_NoCart { get; set; }
        public string Banks_NoIR { get; set; }
        public string Banks_NoBank { get; set; }
        public int Banks_NameID { get; set; }
        public int Banks_Userid { get; set; }
        public string Banks_Nameuser { get; set; }
    
        public virtual Tbl_BankeName Tbl_BankeName { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
