//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storenarm2.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Product()
        {
            this.Tbl_Bill = new HashSet<Tbl_Bill>();
            this.Tbl_Download = new HashSet<Tbl_Download>();
            this.Tbl_InterimBill = new HashSet<Tbl_InterimBill>();
            this.Tbl_Pic = new HashSet<Tbl_Pic>();
            this.Tbl_Tags = new HashSet<Tbl_Tags>();
        }
    
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Text { get; set; }
        public int Product_Price { get; set; }
        public Nullable<int> Product_Off { get; set; }
        public string Product_PicIndex { get; set; }
        public bool Product_IsDownload { get; set; }
        public System.DateTime Product_Date { get; set; }
        public Nullable<int> Product_Groupid { get; set; }
        public bool Product_AllOff { get; set; }
        public int Product_Visit { get; set; }
        public Nullable<int> Product_ExitCount { get; set; }
        public Nullable<int> Product_Weight { get; set; }
        public int Product_Userid { get; set; }
        public bool Product_Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Bill> Tbl_Bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Download> Tbl_Download { get; set; }
        public virtual Tbl_Group Tbl_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_InterimBill> Tbl_InterimBill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Pic> Tbl_Pic { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Tags> Tbl_Tags { get; set; }
    }
}
