//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storenarm2.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ConfirmEmail
    {
        public int ConfirmEamil_ID { get; set; }
        public System.DateTime ConfirmEamil_Date { get; set; }
        public int ConfirmEamil_Userid { get; set; }
        public bool ConfirmEamil_Status { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
