//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storenarm2.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Identity
    {
        public int Identity_ID { get; set; }
        public string Identity_Pic { get; set; }
        public string Identity_FathersName { get; set; }
        public string Identity_Birth { get; set; }
        public bool Identity_Confirm { get; set; }
        public int Identity_Userid { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
