//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storenarm2.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User()
        {
            this.Tbl_Bill = new HashSet<Tbl_Bill>();
            this.Tbl_ConfirmEmail = new HashSet<Tbl_ConfirmEmail>();
            this.Tbl_Cooki = new HashSet<Tbl_Cooki>();
            this.Tbl_Download = new HashSet<Tbl_Download>();
            this.Tbl_Identity = new HashSet<Tbl_Identity>();
            this.Tbl_InterimBill = new HashSet<Tbl_InterimBill>();
            this.Tbl_Message = new HashSet<Tbl_Message>();
            this.Tbl_Message1 = new HashSet<Tbl_Message>();
            this.Tbl_NoBank = new HashSet<Tbl_NoBank>();
            this.Tbl_Product = new HashSet<Tbl_Product>();
            this.Tbl_Withdrawal = new HashSet<Tbl_Withdrawal>();
        }
    
        public int User_ID { get; set; }
        public string User_NameFamily { get; set; }
        public string User_Username { get; set; }
        public string User_Email { get; set; }
        public string User_Password { get; set; }
        public string User_Address { get; set; }
        public string User_City { get; set; }
        public string User_PostalCode { get; set; }
        public string User_Tel { get; set; }
        public string User_Mobile { get; set; }
        public System.DateTime User_Date { get; set; }
        public bool User_Active { get; set; }
        public string User_Rating { get; set; }
        public int User_Roleid { get; set; }
        public string User_NationalCode { get; set; }
        public int User_Stateid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Bill> Tbl_Bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ConfirmEmail> Tbl_ConfirmEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Cooki> Tbl_Cooki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Download> Tbl_Download { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Identity> Tbl_Identity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_InterimBill> Tbl_InterimBill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Message> Tbl_Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Message> Tbl_Message1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_NoBank> Tbl_NoBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Product> Tbl_Product { get; set; }
        public virtual Tbl_Role Tbl_Role { get; set; }
        public virtual Tbl_State Tbl_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Withdrawal> Tbl_Withdrawal { get; set; }
    }
}
