//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storenarm2.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Bill()
        {
            this.Tbl_TempDL = new HashSet<Tbl_TempDL>();
        }
    
        public int Bill_Id { get; set; }
        public System.DateTime Bill_Date { get; set; }
        public int Bill_Productid { get; set; }
        public int Bill_Buyer { get; set; }
        public int Bill_Seller { get; set; }
        public int Bill_Postage { get; set; }
        public int Bill_PayPrice { get; set; }
        public int InvoiceNumber { get; set; }
        public string Bill_TransNo { get; set; }
        public string Bill_RefNo { get; set; }
        public Nullable<bool> Bill_Status { get; set; }
        public string Bill_TrackingCode { get; set; }
        public Nullable<int> Bill_PostStatusid { get; set; }
        public int Bill_Price { get; set; }
        public System.DateTime Bill_ExpDate { get; set; }
        public int Bill_Count { get; set; }
    
        public virtual Tbl_PostStatus Tbl_PostStatus { get; set; }
        public virtual Tbl_Product Tbl_Product { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TempDL> Tbl_TempDL { get; set; }
    }
}
