//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storenarm2.Models.Domins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TempDL
    {
        public int TepmDl_ID { get; set; }
        public System.DateTime TepmDl_Date { get; set; }
        public System.DateTime TepmDl_Exp { get; set; }
        public string TepmDl_UniqNo { get; set; }
        public int TepmDl_BillNo { get; set; }
    
        public virtual Tbl_Bill Tbl_Bill { get; set; }
    }
}
